// services/reportService.js
import OpenAI from "openai";
import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 🧹 Text cleaner — removes markdown, bullets, hashes
function cleanText(str = "") {
  return String(str)
    .replace(/^(\s*\d+[\.\)]\s*)/gm, "")
    .replace(/^(\s*[-*+>]+\s*)/gm, "")
    .replace(/[#*_`>~]/g, "")
    .replace(/\r/g, "")
    .replace(/\s{2,}/g, " ")
    .replace(/\n{2,}/g, "\n")
    .trim();
}

export async function generateAndStoreReport({ pool, user_id, session_id, answers }) {
  // Fetch user info
  const userRes = await pool.query(
    "SELECT full_name, email FROM users WHERE user_id = $1",
    [user_id]
  );
  const fullName = userRes.rows[0]?.full_name || "User";
  const email = userRes.rows[0]?.email;

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  // 🧠 Prompt for structured report
  const prompt = `
You are a professional marketing auditor. Generate a clear, consistent report in plain text — no markdown, no bullets, no numbered lists.
All sections should have similar paragraph length and tone (formal, executive style). 

Structure (keep consistent style and simple formatting):
1. Executive Summary
2. Strengths
3. Weaknesses
4. Opportunities
5. Strategic Recommendations
6. Marketing Maturity Score (0–100)
7. Conclusion

Guidelines:
- Each paragraph should be 4–6 sentences, concise, and readable.
- Keep all font sizes uniform; no bold or headings.
- Use professional but simple business English.

User responses:
${answers.map((a, i) => `${i + 1}. ${a}`).join("\n")}
`;

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: "You are a professional marketing auditor AI. Produce plain, simple text with consistent paragraph size and tone." },
      { role: "user", content: prompt },
    ],
    temperature: 0.6,
    max_tokens: 1600,
  });

  // 🧾 Clean text and strip markdown
  let reportText = completion.choices[0].message.content.trim();
  reportText = cleanText(reportText);

  // 📁 Prepare directories
  const reportsDir = path.join(__dirname, "../reports");
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir);

  const safeName = fullName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  const fileName = `${safeName}_AI_Audit_Report.pdf`;
  const filePath = path.join(reportsDir, fileName);

  // 🧾 Create professional PDF
  const doc = new PDFDocument({ margin: 50 });
  const writeStream = fs.createWriteStream(filePath);
  doc.pipe(writeStream);

  // Title (Red)
  doc.font("Helvetica-Bold").fontSize(24).fillColor("#C62828")
    .text("AI Marketing Audit Report", { align: "center" });
  doc.moveDown(0.5);
  doc.font("Helvetica").fontSize(12).fillColor("#555")
    .text(`Generated for: ${fullName}`, { align: "center" });
  doc.moveDown(1);
  doc.strokeColor("#C62828").lineWidth(1.5).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(1);

  // Body (uniform font)
  doc.font("Helvetica").fontSize(12).fillColor("black");
  const paragraphs = reportText.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean);
  paragraphs.forEach((p) => {
    doc.text(p, {
      align: "justify",
      lineGap: 6,
      paragraphGap: 8,
    });
    doc.moveDown(0.3);
  });

  // Footer
  doc.moveDown(2);
  doc.font("Helvetica-Oblique").fontSize(10).fillColor("#777")
    .text("Generated by AI-AUDIT © A2X CORP", { align: "center" });

  doc.end();
  await new Promise((resolve) => writeStream.on("finish", resolve));

  // 💾 Store in database
  const insertQuery = `
    INSERT INTO generatedreports (session_id, user_id, file_path, report_title, generated_at)
    VALUES ($1, $2, $3, $4, NOW())
    RETURNING report_id
  `;
  const result = await pool.query(insertQuery, [
    session_id,
    user_id,
    filePath,
    "AI Marketing Audit Report",
  ]);

  return { 
    report_id: result.rows[0].report_id, 
    file_path: filePath, 
    fullName, 
    email 
  };
}
